---
- name: Converge
  hosts: all
  become: yes
  become_user: ansible

  roles:
    - role: ruby
      vars:
        ruby_install_method: make_unprivileged
        ruby_gems_user_install: yes

# vim: set ft=yaml.ansible :
