---
- name: Prepare
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Adjust path
      copy:
        dest: /etc/profile.d/set_path.sh
        content: |
          export PATH="$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:bin"
        mode: 0644

    - name: Update apt-get cache
      apt:
        update_cache: yes
        cache_valid_time: 0
      when: ansible_os_family.lower() == 'debian'

    - name: Update pacman cache
      pacman:
        update_cache: yes
      when: ansible_os_family.lower() == 'archlinux'

    - name: Update yum cache
      yum:
        update_cache: yes
      when: ansible_os_family.lower() == 'redhat'

# vim: set ft=yaml.ansible :
